#! /bin/bash

gcc -c src/xengine_applib.c
gcc -c src/Xengine.c
gcc -o Xengine -Wall -Wextra -pedantic xengine_applib.o Xengine.o -lncurses -lpthread
rm -f xengine_applib.o
rm -f Xengine.o

if [[ $1 == "-r" ]] 
then
	./Xengine
	rm -f Xengine
fi
